import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Amplify } from 'aws-amplify';
import { myAppConfig } from '../apiConfig/apiConfiguration';
import { getTranslations } from '../queries/translations/translations';
import Translation from '../interfaces/translation.interface';
import { useContext, useEffect, useState } from 'react';
import HomePage from './home/HomePage';

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  )
}

export default Home
