import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getTranslations } from '../queries/translations/translations';
import Translation from '../interfaces/translation.interface';
import { useContext, useEffect} from 'react';
import HomePage from './home/HomePage';
import { contextProps } from '../interfaces/contextProps.interface';
import { context } from '../context/ContextProvider';

export async function getServerSideProps(){
  let data:any = [];
  try{
    data = await getTranslations('es');
    const {data:{listTranslations}}:{data:any, listTranslation:[Translation]} = await data;
    return{
      props:{listTranslations}
    }
  }catch(error){
    console.log(error)
  }  
}

const Home: NextPage = ({listTranslations}:any) => {

  const {setApiData} = useContext<contextProps>(context);

  useEffect(()=>{
    //To avoid the refresh listTtanslations when click from About Section to Home
    if(localStorage.getItem('preferLang') === null){
      setApiData(listTranslations);
    }
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  )
}

export default Home
